### ISSUE TITLE
Company name with apostrophe

### ISSUE THREAD

**Issue by kab00kie** [wpentester/Linkedin_profiles#1]
Hello.  Firstly, thank you very much for such a great tool.

I'm trying to scrape a company with at least 1000 employees on LinkedIn for a pentest and having issues getting the script to locate the correct page.  Not sure if this is an apostrophe issue or if the client I am trying this for has a name that's too similar to other companies.

I've tried the name in quotes and using \ to escape the apostrophe but still no luck.  As far as I can tell from searching manually and going to Companies, it is the first on the list, but the script wants to pull the 3rd/4th result.

Do you have any advice?  Or is there another way I can provide the page via URL and go directly to it?

Thank you!

PS. I'm happy to open a separate issue for this if you'd like, but this company has affiliate organizations.  I've scraped two _very_ successfully but for the third I am getting this when trying to generate emails from the HTML:

Traceback (most recent call last):
  File "linkedin_profiles.py", line 258, in <module>
    main()
  File "linkedin_profiles.py", line 249, in main
    pp.print_employees()
  File "linkedin_profiles.py", line 170, in print_employees
    fname = re.sub('[^A-Za-z]+', '', fname)
UnboundLocalError: local variable 'fname' referenced before assignment

I understand the error in theory but unsure why it's popping up for this.  I've referenced first.last for the email format.

I've retested the first two to be sure that I didn't mess anything up and they still seem to be fine.  I can write something hacky to get through it but thought I'd try adding it in while I was opening an issue for the above.  Thank you again.

**Comment by wpentester** [comment]
Hi Kab00kie,

Your first issue might be any number of things because this script is a work in progress.  I added the command-line options the day I made it available on Github because before then, I was just editing the code itself when I needed to pull a new company.  I've run into several different issues in the past with different company names as well.  I usually have just taken the apostrophe out of the name.  

If you know the URL for viewing the company's employees, you can add it directly to the code itself on line 69:

employees_page = <your company's url here>

When you rerun the program, it will use your company's url instead of the discovered one.

**Comment by kab00kie** [comment]
Works like a charm.  Thank you very much for your response and help!

I was wondering how I could use/modify your tool to scrape more than 1000 people with the 100 pages limit.  Now that I can manually set the link I imagine I can also set advanced filters and then feed that to the tool.  Awesome!
